# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-chipseq-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - r-base=3.4.1
  - r-optparse=1.6.0
  - r-rcolorbrewer=1.1_2
  - r-ggplot2=3.1.0
  - r-reshape2=1.4.3
  - r-scales=1.0.0
  - r-pheatmap=1.0.10
  - r-lattice=0.20_35
  - r-upsetr=1.3.3
  - r-xfun=0.6

  ## bioconda packages
  - fastqc=0.11.8
  - trim-galore=0.5.0
  - bwa=0.7.17
  - samtools=1.9
  - picard=2.19.0
  - bamtools=2.5.1
  - pysam=0.15.2
  - bedtools=2.27.1
  - ucsc-bedgraphtobigwig=377
  - deeptools=3.2.1
  - macs2=2.1.2
  - homer=4.9.1
  - subread=1.6.4
  - phantompeakqualtools=1.2
  - multiqc=1.7
  - bioconductor-deseq2=1.20.0
  - bioconductor-vsn=3.46.0
