# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-chipseq-1.2.0
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::python=3.7.6
  - conda-forge::markdown=3.1.1
  - conda-forge::pymdown-extensions=6.0
  - conda-forge::pygments=2.5.2
  - conda-forge::r-base=3.6.2
  - conda-forge::r-optparse=1.6.4
  - conda-forge::r-rcolorbrewer=1.1_2
  - conda-forge::r-ggplot2=3.2.1
  - conda-forge::r-tidyr=1.0.2
  - conda-forge::r-scales=1.1.0
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-lattice=0.20_40
  - conda-forge::r-upsetr=1.4.0
  - conda-forge::r-xfun=0.12
  - conda-forge::gawk=5.0.1
  - conda-forge::pigz=2.3.4               ## Required for TrimGalore multi-threading

  ## bioconda packages
  - bioconda::fastqc=0.11.9
  - bioconda::trim-galore=0.6.5
  - bioconda::bwa=0.7.17
  - bioconda::samtools=1.9
  - bioconda::picard=2.21.9
  - bioconda::bamtools=2.5.1
  - bioconda::pysam=0.15.4
  - bioconda::bedtools=2.29.2
  - bioconda::ucsc-bedgraphtobigwig=357
  - bioconda::deeptools=3.3.2
  - bioconda::macs2=2.2.6
  - bioconda::homer=4.10
  - bioconda::subread=2.0.0
  - bioconda::phantompeakqualtools=1.2.2
  - bioconda::preseq=2.0.3
  - bioconda::multiqc=1.8
  - bioconda::bioconductor-biocparallel=1.20.0
  - bioconda::bioconductor-deseq2=1.26.0
  - bioconda::bioconductor-vsn=3.54.0
