# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-chipseq-1.4dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - conda-forge::openjdk=8.0.144 # Needed for FastQC - conda build hangs without this
  - fastqc=0.11.7
  - trim-galore=0.5.0
  - bwa=0.7.17
  - conda-forge::gawk=4.2.1
  - conda-forge::r-markdown=0.8
  - bioconda::r-spp=1.15.2
  - bedtools=2.27.1
  - samtools=1.9
  - picard=2.18.11
  - deeptools=3.1.1
  - macs2=2.1.1.20160309
  - multiqc=1.6
  - conda-forge::r-catools=1.17.1.1
  - conda-forge::r-snow=0.4_2
  - conda-forge::r-r.utils=2.6.0
  - conda-forge::r-stringr=1.3.1
  - conda-forge::r-markdown=0.8
  - conda-forge::r-evaluate=0.10.1
  - conda-forge::r-domc=1.3.5
  - conda-forge::r-ggplot2=3.0.0
  - conda-forge::r-knitr=1.20
  - conda-forge::r-rmysql=0.10.13
  - conda-forge::r-doparallel=1.0.11
  - bioconda::bioconductor-bsgenome=1.46.0
  - bioconda::bioconductor-rsamtools=1.30.0
  - bioconda::bioconductor-shortread=1.36.0
  - bioconda::bioconductor-genomicranges=1.30.3
  - bioconda::bioconductor-genomicfeatures=1.30.3
  - bioconda::bioconductor-ensembldb=2.2.2
  - bioconda::bioconductor-chippeakanno=3.12.0
  - bioconda::bioconductor-biomart=2.34.2
  - bioconda::bioconductor-rtracklayer=1.38.3
  - bioconda::bioconductor-bsgenome.hsapiens.ucsc.hg19=1.4.0
  - bioconda::bioconductor-org.hs.eg.db=3.5.0
  - bioconda::bioconductor-bsgenome.mmusculus.ucsc.mm10=1.4.0
  - bioconda::bioconductor-org.mm.eg.db=3.5.0
  - bioconda::r-spp=1.15.2
  - bioconda::r-ngsplot=2.63
  - bioconda::r-ngsplotdb-hg19=3.00
  - bioconda::r-ngsplotdb-hg38=3.00
  - bioconda::r-ngsplotdb-mm10=3.00
