# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-chipseq-1.1.1dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - gawk=5.0.1
  - r-base=3.6.1
  - r-optparse=1.6.4
  - r-rcolorbrewer=1.1_2
  - r-ggplot2=3.2.1
  - r-reshape2=1.4.3
  - r-scales=1.0.0
  - r-pheatmap=1.0.12
  - r-lattice=0.20_38
  - r-upsetr=1.4.0
  - r-xfun=0.11
  - r-stringi=1.4.3

  ## bioconda packages
  - fastqc=0.11.8
  - trim-galore=0.6.4
  - bwa=0.7.17
  - samtools=1.9
  - picard=2.21.3
  - bamtools=2.5.1
  - pysam=0.15.3
  - bedtools=2.29.0
  - ucsc-bedgraphtobigwig=357
  - deeptools=3.3.1
  - macs2=2.2.5
  - genrich=0.6
  - homer=4.10
  - subread=1.6.4
  - phantompeakqualtools=1.2.1.1
  - preseq=2.0.3
  - multiqc=1.7
  - bioconductor-deseq2=1.26.0
  - bioconductor-vsn=3.54.0
