# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-chipseq-1.3.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::python=3.7.8
  - conda-forge::markdown=3.2.2
  - conda-forge::pymdown-extensions=7.1
  - conda-forge::pygments=2.6.1
  - conda-forge::r-base=4.0.2
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-rcolorbrewer=1.1_2
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-tidyr=1.1.0
  - conda-forge::r-scales=1.1.1
  - conda-forge::r-pheatmap=1.0.12
  - conda-forge::r-lattice=0.20_41
  - conda-forge::r-upsetr=1.4.0
  - conda-forge::r-xfun=0.16

  ## bioconda packages
  - bioconda::samtools=1.10
  - bioconda::bamtools=2.5.1
  - bioconda::pysam=0.16.0.1
  - bioconda::bedtools=2.29.2
  - bioconda::bioconductor-biocparallel=1.22.0
  - bioconda::bioconductor-deseq2=1.28.0
  - bioconda::bioconductor-vsn=3.56.0
