name: nf-core AWS test
# This workflow is triggered on PRs to the master branch.
# It runs the -profile 'test_full' on AWS batch

on:
  push:
    branches:
      - master
      - dev
  release:
    types: [published]

jobs:
  run-awstest:
    if: github.repository == 'nf-core/chipseq'
    name: Run AWS test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v1.0.2
        with:
          auto-update-conda: true
          python-version: 3.7
      - name: Install awscli
        run: conda install -c conda-forge awscli
      - name: Start AWS batch job
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_KEY_SECRET}}
          TOWER_ACCESS_TOKEN: ${{secrets.TOWER_ACCESS_TOKEN}}
        run: | # Submits job to AWS batch using a 'nextflow-4GiB' instance. Setting JVM options to "-XX:+UseG1GC" for more efficient garbage collection when staging remote files.
          aws batch submit-job \
          --region eu-west-1 \
          --job-name nf-core-chipseq \
          --job-queue 'default-8b3836e0-5eda-11ea-96e5-0a2c3f6a2a32' \
          --job-definition nextflow-4GiB \
          --container-overrides '{"command": ["nf-core/chipseq", "-r '"${GITHUB_SHA}"' -profile test_full --outdir s3://nf-core-awsmegatests/chipseq/results-'"${GITHUB_SHA}"' -w s3://nf-core-awsmegatests/chipseq/work-'"${GITHUB_SHA}"' -with-tower"], "environment": [{"name": "TOWER_ACCESS_TOKEN", "value": "'"$TOWER_ACCESS_TOKEN"'"}, {"name": "NXF_OPTS", "value": "-XX:+UseG1GC"}]}'
